export const CountryList = [
    'Afghanistan (+93)',
    'Albania  (+355)',
    'Algeria (+213)',
    'American Samoa (+1)',
    'Andorra (+376)',
    'Angola (+244)',
    'Anguilla (+1)',
    'Antigua and Barbuda',
    'Argentina (+54)',
    'Armenia (+374)',
    'Aruba (+297)',
    'Australia (+61)',
    'Austria (+43)',
    'Azerbaijan (+994)',
    'Bahamas (+1)',
    'Bahrain (+973)',
    'Bangladesh (+880)',
    'Barbados (+246)',
    'Belarus (+375)',
    'Belgium (+32)',
    'Belize (+501)',
    'Benin (+229)',
    'Bermuda (+1)',
    'Bhutan (+975)',
    'Bolivia (+591)',
    'Bosnia and Herzegovina (+387)',
    'Botswana (+267)',
    'Brazil (+55)',
    'Brunei Darussalam (+673)',
    'Bulgaria (+359)',
    'Burkina Faso (+226)',
    'Burundi (+257)',
    'Cambodia (+855)',
    'Cameroon (+237)',
    'Canada (+011)',
    'Cape Verde (+238)',
    'Cayman Islands (+345)',
    'Central African Republic (+236)',
    'Chad (+235)',
    'Chile (+56)',
    'China (+86)',
    'Christmas Island (+0011)',
    'Cocos (+Keeling)Islands (+0011)',
    'Colombia (+57)',
    'Comoros (+269)',
    'Congo Brazzaville (+242)',
    'CongoKinshasa (+243)',
    'Cook Islands (+682)',
    'Costa Rica (+506)',
    'Côte DIvoire  (+Ivory Coast) (+225)',
    'Croatia (+Hrvatska) (+385)',
    'Cuba (+53)',
    'Cyprus (+357)',
    'Czech Republic (+420)',
    'Denmark (+45)',
    'Djibouti (+253)',
    'Dominica (+767)',
    'Dominican Republic (+809)',
    'Ecuador (+593)',
    'Egypt (+20)',
    'El Salvador (+503)',
    'Equatorial Guinea (+240)',
    'Eritrea (+291)',
    'Estonia (+372)',
    'Ethiopia (+251)',
    'Falkland Islands (+Malvinas) (+500)',
    'Faroe Islands (+298)',
    'Fiji (+679)',
    'Finland (+358)',
    'France (+33)',
    'French Guiana (+594)',
    'French Polynesia (+689)',
    'Gabon (+241)',
    'Gambia (+220)',
    'Georgia (+995)',
    'Germany (+49)',
    'Ghana (+233)',
    'Gibraltar (+350)',
    'Greece (+30)',
    'Greenland (+299)',
    'Grenada (+473)',
    'Guadeloupe (+590)',
    'Guam (+671)',
    'Guatemala (+502)',
    'Guinea (+224)',
    'Guinea - Bissau (+245)',
    'Guyana (+592)',
    'Haiti (+509)',
    'Holy (+379)',
    'Honduras (+504)',
    'Hong Kong', 'SAR (+852)',
    'Hungary (+36)',
    'Iceland (+354)',
    'India (+91)',
    'Indonesia (+62)',
    'Iran, Islamic Republic of (+98)',
    'Iraq (+964)',
    'Ireland (+353)',
    'Israel (+972)',
    'Italy (+39)',
    'Jamaica (+876)',
    'Japan (+81)',
    'Jordan (+962)',
    'Kazakhstan (+810)',
    'Kenya (+254)',
    'Kiribati (+686)',
    'Korea, Democratic Peoples Republic of  (+North) (+850)',
    'Korea, Republic of (+South)  (+82)',
    'Kuwait (+965)',
    'Kyrgyzstan (+996)',
    'Laos (+Lao PDR) (+856)',
    'Latvia (+371)',
    'Lebanon (+961)',
    'Lesotho (+266)',
    'Liberia (+231)',
    'Libya (+218)',
    'Liechtenstein (+423)',
    'Lithuania (+370)',
    'Luxembourg	 (+352)',
    'Macao (+SARChina) (+853)',
    'Macedonia (+389)',
    'Madagascar (+261)',
    'Malawi (+265)',
    'Malaysia (+60)',
    'Maldives (+960)',
    'Mali (+223)',
    'Malta (+356)',
    'Marshall Islands (+692)',
    'Martinique (+596)',
    'Mauritania (+222)',
    'Mauritius (+230)',
    'Mayotte (+262)',
    'Mexico (+52)',
    'Micronesia FeDerated States of (+691)',
    'Moldova (+373)',
    'Monaco (+377)',
    'Mongolia (+976)',
    'Montenegro (+382)',
    'Montserrat (+664)',
    'Morocco and Western Sahara (+212)',
    'Mozambique (+258)',
    'Myanmar (+95)',
    'Namibia (+264)',
    'Nauru (+674)',
    'Nepal (+977)',
    'Netherlands (+31)',
    'NetheRlands Antilles (+599)',
    ' New Caledonia (+687)',
    'New Zealand (+64)',
    'Nicaragua (+505)',
    'Niger (+227)',
    'Nigeria (+234)',
    'Niue (+683)',
    'Norfolk Island (+672)',
    'Northern Mariana Islands (+670)',
    'Norway (+47)',
    'Oman (+968)',
    'Pakistan (+92)',
    'Palau (+680)',
    'Palestinian Territory', 'Occupied (+970)',
    'Panama (+507)',
    'Papua New Guinea (+675)',
    'Paraguay (+595)',
    'Peru (+51)',
    'Philippines (+63)',
    'Pitcairn (+870)',
    'Poland (+48)',
    'Portugal (+351)',
    'Puerto Rico (+787)',
    'Qatar (+974)',
    'Réunion and Mayotte (+262)',
    'Romania (+40)',
    'Russian Federation (+810)',
    'Rwanda (+250)',
    'Saint Helena and also Tristan Da Cunha (+290)',
    'Saint Kitts and Nevis (+869)',
    'Saint Lucia (+758)',
    'Saint Pierre and Miquelon (+508)',
    ' Saint Vincent and the Grenadines (+784)',
    'Samoa (+685)',
    'San Marino (+378)',
    'São Tomé and Principe (+239)',
    'Saudi Arabia (+966)',
    'Senegal (+221)',
    'Serbia (+381)',
    'Seychelles	 (+248)',
    'Sierra Leone (+232)',
    'Singapore (+65)',
    'Slovakia (+421)',
    'Slovenia (+386)',
    'Solomon Islands (+677)',
    'Somalia (+252)',
    'South Africa (+27)',
    'Spain (+34)',
    'Sri Lanka (+94)',
    'Sudan (+249)',
    'Suriname (+597)',
    'Svalbard and Jan Mayen Islands (+47)',
    'Swaziland (+268)',
    'Sweden (+46)',
    'Switzerland (+41)',
    'Syrian Arab Republic (+Syria) (+963)',
    'Taiwan Republic of China (+886)',
    'Tajikistan (+992)',
    'Tanzania United Republic of (+255)',
    'Thailand (+66)',
    'Timor Leste (+670)',
    'Togo (+228)',
    'Tokelau (+690)',
    'Tonga (+676)',
    'Trinidad and Tobago (+868)',
    'Tunisia (+216)',
    'Turkey (+90)',
    'Turkmenistan  (+993)',
    'Turks and Caicos Islands (+1)',
    'Tuvalu (+688)',
    'Uganda (+256)',
    'Ukraine (+380)',
    'United Arab Emirates (+971)',
    'United Kingdom (+44)',
    'United States of America (+1)',
    'Uruguay (+598)',
    'Uzbekistan (+998)',
    'Vanuatu (+678)',
    'Venezuela (+Bolivarian Republic of) (+58)',
    'Viet Nam (+84)',
    'Virgin Islands British (+284)',
    'Virgin Islands US (+340)',
    'Wallis and Futuna Islands (+681)',
    'Yemen (+967)',
    'Zambia (+260)',
    'Zimbabwe (+263)',
]

export const CountryDetails = [
    { code: 'AF', label: 'Afghanistan', phone: '93', phoneLength: 9 },
    { code: 'AL', label: 'Albania', phone: '355', phoneLength: 9 },
    { code: 'DZ', label: 'Algeria', phone: '213', phoneLength: 9 },
    { code: 'AS', label: 'American Samoa', phone: '1-684', phoneLength: 10 },
    { code: 'AD', label: 'Andorra', phone: '376', phoneLength: 6 },
    { code: 'AO', label: 'Angola', phone: '244', phoneLength: 9 },
    { code: 'AI', label: 'Anguilla', phone: '1-264', phoneLength: 10 },
    { code: 'AQ', label: 'Antarctica', phone: '672', phoneLength: 6 },
    { code: 'AG', label: 'Antigua and Barbuda', phone: '1-268', phoneLength: 10 },
    { code: 'AR', label: 'Argentina', phone: '54', phoneLength: 8 },
    { code: 'AM', label: 'Armenia', phone: '374', phoneLength: 6 },
    { code: 'AW', label: 'Aruba', phone: '297', phoneLength: 7 },
    { code: 'AU', label: 'Australia', phone: '61', suggested: true, phoneLength: 9 },
    { code: 'AT', label: 'Austria', phone: '43', phoneLength: 5 },
    { code: 'AZ', label: 'Azerbaijan', phone: '994', phoneLength: 9 },
    { code: 'BS', label: 'Bahamas', phone: '1-242', phoneLength: 10 },
    { code: 'BH', label: 'Bahrain', phone: '973', phoneLength: 8 },
    { code: 'BD', label: 'Bangladesh', phone: '880', phoneLength: 10 },
    { code: 'BB', label: 'Barbados', phone: '1-246', phoneLength: 10 },
    { code: 'BY', label: 'Belarus', phone: '375', phoneLength: 9 },
    { code: 'BE', label: 'Belgium', phone: '32', phoneLength: 9 },
    { code: 'BZ', label: 'Belize', phone: '501', phoneLength: 7 },
    { code: 'BJ', label: 'Benin', phone: '229', phoneLength: 8 },
    { code: 'BM', label: 'Bermuda', phone: '1-441', phoneLength: 10 },
    { code: 'BT', label: 'Bhutan', phone: '975', phoneLength: 7 },
    { code: 'BO', label: 'Bolivia', phone: '591', phoneLength: 9 },
    { code: 'BQ', label: 'Bonaire, Sint Eustatius and Saba', phone: '599', phoneLength: 7 },
    { code: 'BA', label: 'Bosnia and Herzegovina', phone: '387', phoneLength: 8 },
    { code: 'BW', label: 'Botswana', phone: '267', phoneLength: 7 },
    { code: 'BR', label: 'Brazil', phone: '55', phoneLength: 11 },
    { code: 'IO', label: 'British Indian Ocean Territory', phone: '246', phoneLength: 7 },
    { code: 'BN', label: 'Brunei Darussalam', phone: '673', phoneLength: 7 },
    { code: 'BG', label: 'Bulgaria', phone: '359', phoneLength: 9 },
    { code: 'BF', label: 'Burkina Faso', phone: '226', phoneLength: 8 },
    { code: 'BI', label: 'Burundi', phone: '257', phoneLength: 8 },
    { code: 'KH', label: 'Cambodia', phone: '855', phoneLength: 9 },
    { code: 'CM', label: 'Cameroon', phone: '237', phoneLength: 9 },
    { code: 'CA', label: 'Canada', phone: '1', suggested: true, phoneLength: 10 },
    { code: 'CV', label: 'Cape Verde', phone: '238', phoneLength: 7 },
    { code: 'KY', label: 'Cayman Islands', phone: '1-345', phoneLength: 7 },
    { code: 'CF', label: 'Central African Republic', phone: '236', phoneLength: 8 },
    { code: 'TD', label: 'Chad', phone: '235', phoneLength: 6 },
    { code: 'CL', label: 'Chile', phone: '56', phoneLength: 9 },
    { code: 'CN', label: 'China', phone: '86', phoneLength: 11 },
    { code: 'CX', label: 'Christmas Island', phone: '61', phoneLength: 9 },
    { code: 'CC', label: 'Cocos (Keeling) Islands', phone: '61', phoneLength: 10 },
    { code: 'CO', label: 'Colombia', phone: '57', phoneLength: 10 },
    { code: 'KM', label: 'Comoros', phone: '269', phoneLength: 7 },
    { code: 'CG', label: 'Congo, Republic of the', phone: '242', phoneLength: 9 },
    { code: 'CD', label: 'Congo, Democratic Republic of the', phone: '243', phoneLength: 7 },
    { code: 'CK', label: 'Cook Islands', phone: '682', phoneLength: 5 },
    { code: 'CR', label: 'Costa Rica', phone: '506', phoneLength: 8 },
    { code: 'HR', label: 'Croatia', phone: '385', phoneLength: 9 },
    { code: 'CU', label: 'Cuba', phone: '53', phoneLength: 8 },
    { code: 'CW', label: 'Curacao', phone: '599', phoneLength: 7 },
    { code: 'CY', label: 'Cyprus', phone: '357', phoneLength: 8 },
    { code: 'CZ', label: 'Czech Republic', phone: '420', phoneLength: 9 },
    { code: 'DK', label: 'Denmark', phone: '45', phoneLength: 8 },
    { code: 'DJ', label: 'Djibouti', phone: '253', phoneLength: 10 },
    { code: 'DM', label: 'Dominica', phone: '1-767', phoneLength: 10 },
    { code: 'DO', label: 'Dominican Republic', phone: '1-809', phoneLength: 10 },
    { code: 'TL', label: 'East Timor', phone: '670', phoneLength: 7 },
    { code: 'EC', label: 'Ecuador', phone: '593', phoneLength: 9 },
    { code: 'EG', label: 'Egypt', phone: '20', phoneLength: 10 },
    { code: 'SV', label: 'El Salvador', phone: '503', phoneLength: 8 },
    { code: 'GQ', label: 'Equatorial Guinea', phone: '240', phoneLength: 7 },
    { code: 'ER', label: 'Eritrea', phone: '291', phoneLength: 7 },
    { code: 'EE', label: 'Estonia', phone: '372', phoneLength: 7 },
    { code: 'ET', label: 'Ethiopia', phone: '251', phoneLength: 9 },
    { code: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500', phoneLength: 5 },
    { code: 'FO', label: 'Faroe Islands', phone: '298', phoneLength: 6 },
    { code: 'FJ', label: 'Fiji', phone: '679', phoneLength: 7 },
    { code: 'FI', label: 'Finland', phone: '358', phoneLength: 10 },
    { code: 'FR', label: 'France', phone: '33', phoneLength: 9 },
    { code: 'GF', label: 'French Guiana', phone: '594', phoneLength: 9 },
    { code: 'PF', label: 'French Polynesia', phone: '689', phoneLength: 6 },
    { code: 'TF', label: 'French Southern Territories', phone: '262', phoneLength: 9 },
    { code: 'GA', label: 'Gabon', phone: '241', phoneLength: 6 },
    { code: 'GM', label: 'Gambia', phone: '220', phoneLength: 7 },
    { code: 'GE', label: 'Georgia', phone: '995', phoneLength: 8 },
    { code: 'DE', label: 'Germany', phone: '49', phoneLength: 10 },
    { code: 'GH', label: 'Ghana', phone: '233', phoneLength: 9 },
    { code: 'GI', label: 'Gibraltar', phone: '350', phoneLength: 8 },
    { code: 'GR', label: 'Greece', phone: '30', phoneLength: 10 },
    { code: 'GL', label: 'Greenland', phone: '299', phoneLength: 6 },
    { code: 'GD', label: 'Grenada', phone: '1-473', phoneLength: 10 },
    { code: 'GP', label: 'Guadeloupe', phone: '590', phoneLength: 9 },
    { code: 'GU', label: 'Guam', phone: '1-671', phoneLength: 10 },
    { code: 'GT', label: 'Guatemala', phone: '502', phoneLength: 8 },
    { code: 'GG', label: 'Guernsey', phone: '44', phoneLength: 10 },
    { code: 'GN', label: 'Guinea', phone: '224', phoneLength: 8 },
    { code: 'GW', label: 'Guinea-Bissau', phone: '245', phoneLength: 7 },
    { code: 'GY', label: 'Guyana', phone: '592', phoneLength: 7 },
    { code: 'HT', label: 'Haiti', phone: '509', phoneLength: 8 },
    { code: 'HM', label: 'Heard Island and McDonald Islands', phone: '672', phoneLength: 6 },
    { code: 'VA', label: 'Holy See (Vatican City State)', phone: '379', phoneLength: 5 },
    { code: 'HN', label: 'Honduras', phone: '504', phoneLength: 8 },
    { code: 'HK', label: 'Hong Kong', phone: '852', phoneLength: 8 },
    { code: 'HU', label: 'Hungary', phone: '36', phoneLength: 9 },
    { code: 'IS', label: 'Iceland', phone: '354', phoneLength: 7 },
    { code: 'IN', label: 'India', phone: '91', suggested: true, phoneLength: 10 },
    { code: 'ID', label: 'Indonesia', phone: '62', phoneLength: 11 },
    { code: 'IR', label: 'Iran, Islamic Republic of', phone: '98', phoneLength: 10 },
    { code: 'IQ', label: 'Iraq', phone: '964', phoneLength: 10 },
    { code: 'IE', label: 'Ireland', phone: '353', phoneLength: 9 },
    { code: 'IM', label: 'Isle of Man', phone: '44', phoneLength: 10 },
    { code: 'IL', label: 'Israel', phone: '972', phoneLength: 9 },
    { code: 'IT', label: 'Italy', phone: '39', phoneLength: 10 },
    { code: 'JM', label: 'Jamaica', phone: '1-876', phoneLength: 10 },
    { code: 'JP', label: 'Japan', phone: '81', phoneLength: 10 },
    { code: 'JE', label: 'Jersey', phone: '44', phoneLength: 10 },
    { code: 'JO', label: 'Jordan', phone: '962', phoneLength: 9 },
    { code: 'KZ', label: 'Kazakhstan', phone: '7', phoneLength: 10 },
    { code: 'KE', label: 'Kenya', phone: '254', phoneLength: 9 },
    { code: 'KI', label: 'Kiribati', phone: '686', phoneLength: 5 },
    { code: 'KP', label: 'Korea, Democratic People\'s Republic of', phone: '850', phoneLength: 9 },
    { code: 'KR', label: 'Korea, Republic of', phone: '82', phoneLength: 10 },
    { code: 'KW', label: 'Kuwait', phone: '965', phoneLength: 8 },
    { code: 'KG', label: 'Kyrgyzstan', phone: '996', phoneLength: 9 },
    { code: 'LA', label: 'Lao People\'s Democratic Republic', phone: '856', phoneLength: 8 },
    { code: 'LV', label: 'Latvia', phone: '371', phoneLength: 8 },
    { code: 'LB', label: 'Lebanon', phone: '961', phoneLength: 8 },
    { code: 'LS', label: 'Lesotho', phone: '266', phoneLength: 8 },
    { code: 'LR', label: 'Liberia', phone: '231', phoneLength: 8 },
    { code: 'LY', label: 'Libya', phone: '218', phoneLength: 9 },
    { code: 'LI', label: 'Liechtenstein', phone: '423', phoneLength: 8 },
    { code: 'LT', label: 'Lithuania', phone: '370', phoneLength: 8 },
    { code: 'LU', label: 'Luxembourg', phone: '352', phoneLength: 8 },
    { code: 'MO', label: 'Macao', phone: '853', phoneLength: 8 },
    { code: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', phone: '389', phoneLength: 8 },
    { code: 'MG', label: 'Madagascar', phone: '261', phoneLength: 9 },
    { code: 'MW', label: 'Malawi', phone: '265', phoneLength: 9 },
    { code: 'MY', label: 'Malaysia', phone: '60', phoneLength: 10 },
    { code: 'MV', label: 'Maldives', phone: '960', phoneLength: 7 },
    { code: 'ML', label: 'Mali', phone: '223', phoneLength: 8 },
    { code: 'MT', label: 'Malta', phone: '356', phoneLength: 8 },
    { code: 'MH', label: 'Marshall Islands', phone: '692', phoneLength: 7 },
    { code: 'MQ', label: 'Martinique', phone: '596', phoneLength: 9 },
    { code: 'MR', label: 'Mauritania', phone: '222', phoneLength: 8 },
    { code: 'MU', label: 'Mauritius', phone: '230', phoneLength: 7 },
    { code: 'YT', label: 'Mayotte', phone: '262', phoneLength: 9 },
    { code: 'MX', label: 'Mexico', phone: '52', phoneLength: 10 },
    { code: 'FM', label: 'Micronesia, Federated States of', phone: '691', phoneLength: 7 },
    { code: 'MD', label: 'Moldova, Republic of', phone: '373', phoneLength: 8 },
    { code: 'MC', label: 'Monaco', phone: '377', phoneLength: 8 },
    { code: 'MN', label: 'Mongolia', phone: '976', phoneLength: 8 },
    { code: 'ME', label: 'Montenegro', phone: '382', phoneLength: 8 },
    { code: 'MS', label: 'Montserrat', phone: '1-664', phoneLength: 10 },
    { code: 'MA', label: 'Morocco', phone: '212', phoneLength: 9 },
    { code: 'MZ', label: 'Mozambique', phone: '258', phoneLength: 9 },
    { code: 'MM', label: 'Myanmar', phone: '95', phoneLength: 10 },
    { code: 'NA', label: 'Namibia', phone: '264', phoneLength: 9 },
    { code: 'NR', label: 'Nauru', phone: '674', phoneLength: 5 },
    { code: 'NP', label: 'Nepal', phone: '977', phoneLength: 10 },
    { code: 'NL', label: 'Netherlands', phone: '31', phoneLength: 10 },
    { code: 'AN', label: 'Netherlands Antilles', phone: '599', phoneLength: 9 },
    { code: 'NC', label: 'New Caledonia', phone: '687', phoneLength: 6 },
    { code: 'NZ', label: 'New Zealand', phone: '64', phoneLength: 10 },
    { code: 'NI', label: 'Nicaragua', phone: '505', phoneLength: 8 },
    { code: 'NE', label: 'Niger', phone: '227', phoneLength: 8 },
    { code: 'NG', label: 'Nigeria', phone: '234', phoneLength: 10 },
    { code: 'NU', label: 'Niue', phone: '683', phoneLength: 4 },
    { code: 'NF', label: 'Norfolk Island', phone: '672', phoneLength: 6 },
    { code: 'MP', label: 'Northern Mariana Islands', phone: '1-670', phoneLength: 10 },
    { code: 'NO', label: 'Norway', phone: '47', phoneLength: 8 },
    { code: 'OM', label: 'Oman', phone: '968', phoneLength: 8 },
    { code: 'PK', label: 'Pakistan', phone: '92', phoneLength: 10 },
    { code: 'PW', label: 'Palau', phone: '680', phoneLength: 7 },
    { code: 'PS', label: 'Palestinian Territory, Occupied', phone: '970', phoneLength: 9 },
    { code: 'PA', label: 'Panama', phone: '507', phoneLength: 8 },
    { code: 'PG', label: 'Papua New Guinea', phone: '675', phoneLength: 7 },
    { code: 'PY', label: 'Paraguay', phone: '595', phoneLength: 9 },
    { code: 'PE', label: 'Peru', phone: '51', phoneLength: 9 },
    { code: 'PH', label: 'Philippines', phone: '63', phoneLength: 10 },
    { code: 'PN', label: 'Pitcairn', phone: '64', phoneLength: 10 },
    { code: 'PL', label: 'Poland', phone: '48', phoneLength: 9 },
    { code: 'PT', label: 'Portugal', phone: '351', phoneLength: 9 },
    { code: 'PR', label: 'Puerto Rico', phone: '1-787', phoneLength: 10 },
    { code: 'QA', label: 'Qatar', phone: '974', phoneLength: 8 },
    { code: 'RE', label: 'Réunion', phone: '262', phoneLength: 9 },
    { code: 'RO', label: 'Romania', phone: '40', phoneLength: 9 },
    { code: 'RU', label: 'Russian Federation', phone: '7', phoneLength: 10 },
    { code: 'RW', label: 'Rwanda', phone: '250', phoneLength: 9 },
    { code: 'BL', label: 'Saint Barthélemy', phone: '590', phoneLength: 9 },
    { code: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha', phone: '290', phoneLength: 4 },
    { code: 'KN', label: 'Saint Kitts and Nevis', phone: '1-869', phoneLength: 10 },
    { code: 'LC', label: 'Saint Lucia', phone: '1-758', phoneLength: 10 },
    { code: 'MF', label: 'Saint Martin (French part)', phone: '590', phoneLength: 9 },
    { code: 'PM', label: 'Saint Pierre and Miquelon', phone: '508', phoneLength: 6 },
    { code: 'VC', label: 'Saint Vincent and the Grenadines', phone: '1-784', phoneLength: 10 },
    { code: 'WS', label: 'Samoa', phone: '685', phoneLength: 7 },
    { code: 'SM', label: 'San Marino', phone: '378', phoneLength: 5 },
    { code: 'ST', label: 'Sao Tome and Principe', phone: '239', phoneLength: 7 },
    { code: 'SA', label: 'Saudi Arabia', phone: '966', phoneLength: 9 },
    { code: 'SN', label: 'Senegal', phone: '221', phoneLength: 9 },
    { code: 'RS', label: 'Serbia', phone: '381', phoneLength: 9 },
    { code: 'SC', label: 'Seychelles', phone: '248', phoneLength: 7 },
    { code: 'SL', label: 'Sierra Leone', phone: '232', phoneLength: 8 },
    { code: 'SG', label: 'Singapore', phone: '65', phoneLength: 8 },
    { code: 'SX', label: 'Sint Maarten (Dutch part)', phone: '1-721', phoneLength: 10 },
    { code: 'SK', label: 'Slovakia', phone: '421', phoneLength: 9 },
    { code: 'SI', label: 'Slovenia', phone: '386', phoneLength: 8 },
    { code: 'SB', label: 'Solomon Islands', phone: '677', phoneLength: 7 },
    { code: 'SO', label: 'Somalia', phone: '252', phoneLength: 8 },
    { code: 'ZA', label: 'South Africa', phone: '27', phoneLength: 9 },
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500', phoneLength: 5 },
    { code: 'SS', label: 'South Sudan', phone: '211', phoneLength: 9 },
    { code: 'ES', label: 'Spain', phone: '34', phoneLength: 9 },
    { code: 'LK', label: 'Sri Lanka', phone: '94', phoneLength: 9 },
    { code: 'SD', label: 'Sudan', phone: '249', phoneLength: 9 },
    { code: 'SR', label: 'Suriname', phone: '597', phoneLength: 7 },
    { code: 'SJ', label: 'Svalbard and Jan Mayen', phone: '47', phoneLength: 8 },
    { code: 'SZ', label: 'Swaziland', phone: '268', phoneLength: 8 },
    { code: 'SE', label: 'Sweden', phone: '46', phoneLength: 11 },
    { code: 'CH', label: 'Switzerland', phone: '41', phoneLength: 10 },
    { code: 'SY', label: 'Syrian Arab Republic', phone: '963', phoneLength: 9 },
    { code: 'TW', label: 'Taiwan, Province of China', phone: '886', phoneLength: 9 },
    { code: 'TJ', label: 'Tajikistan', phone: '992', phoneLength: 9 },
    { code: 'TZ', label: 'Tanzania, United Republic of', phone: '255', phoneLength: 9 },
    { code: 'TH', label: 'Thailand', phone: '66', phoneLength: 9 },
    { code: 'TG', label: 'Togo', phone: '228', phoneLength: 8 },
    { code: 'TK', label: 'Tokelau', phone: '690', phoneLength: 5 },
    { code: 'TO', label: 'Tonga', phone: '676', phoneLength: 5 },
    { code: 'TT', label: 'Trinidad and Tobago', phone: '1-868', phoneLength: 10 },
    { code: 'TN', label: 'Tunisia', phone: '216', phoneLength: 8 },
    { code: 'TR', label: 'Turkey', phone: '90', phoneLength: 10 },
    { code: 'TM', label: 'Turkmenistan', phone: '993', phoneLength: 8 },
    { code: 'TC', label: 'Turks and Caicos Islands', phone: '1-649', phoneLength: 10 },
    { code: 'TV', label: 'Tuvalu', phone: '688', phoneLength: 5 },
    { code: 'UG', label: 'Uganda', phone: '256', phoneLength: 9 },
    { code: 'UA', label: 'Ukraine', phone: '380', phoneLength: 9 },
    { code: 'AE', label: 'United Arab Emirates', phone: '971', phoneLength: 9 },
    { code: 'GB', label: 'United Kingdom', phone: '44', suggested: true, phoneLength: 10 },
    { code: 'US', label: 'United States', phone: '1', suggested: true, phoneLength: 10 },
    { code: 'UM', label: 'United States Minor Outlying Islands', phone: '1', phoneLength: 10 },
    { code: 'UY', label: 'Uruguay', phone: '598', phoneLength: 8 },
    { code: 'UZ', label: 'Uzbekistan', phone: '998', phoneLength: 9 },
    { code: 'VU', label: 'Vanuatu', phone: '678', phoneLength: 5 },
    { code: 'VE', label: 'Venezuela, Bolivarian Republic of', phone: '58', phoneLength: 10 },
    { code: 'VN', label: 'Vietnam', phone: '84', phoneLength: 10 },
    { code: 'VG', label: 'Virgin Islands, British', phone: '1-284', phoneLength: 10 },
    { code: 'VI', label: 'Virgin Islands, U.S.', phone: '1-340', phoneLength: 10 },
    { code: 'WF', label: 'Wallis and Futuna', phone: '681', phoneLength: 6 },
    { code: 'EH', label: 'Western Sahara', phone: '212', phoneLength: 9 },
    { code: 'YE', label: 'Yemen', phone: '967', phoneLength: 9 },
    { code: 'ZM', label: 'Zambia', phone: '260', phoneLength: 9 },
    { code: 'ZW', label: 'Zimbabwe', phone: '263', phoneLength: 9 },
];



